### ISSUE TITLE
Node edge curvature is constant

### ISSUE THREAD

**Issue by AKoll** [Palanta/palanta-frontend#2]
Currently, node edges have a constant curvature, independent of the distance it spans. This is unpretty, especially at small distances.
Which design approach might be appropriate?

**Comment by AKoll** [comment]
While slightly unschlafable, a giant svg might make sense. It does at least seem fairly easy to implement, and provides similar unschlafability as the current canvas model does.

**Comment by Pikaju** [comment]
#1
