### ISSUE TITLE
Non-zero scroll offset breaks cursor position handling

### ISSUE THREAD

**Issue by AKoll** [palanta/palanta-frontend#6]
When dragging out a connector edge while the canvas is scrolled, cursor positions are handled incorrectly 
![](https://user-images.githubusercontent.com/31693992/69769050-720c0600-1183-11ea-9573-2170865c5761.png)

**Comment by AKoll** [comment]
Assumably the edge endpoint is still placed relative to the canvas anchor while the cursor position is measured in screen space

**Comment by ProtoNXT** [comment]
This issue has been resolved by adding the canvas' scroll offset to the edge's end position
